app:
  http_port: 8888
  log:
    dir: "logs"
    file: "app.log"
  1C:
    url: ""
    auth_token: ""
  vicidial:
    url: ""
    login: ""
    pass: ""
    max_tries: 5
  auth_key: ""
  auth_getaway_token: ""
  getaway_url: ""